services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: gestor_citas_db_container
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: abc123.
      MARIADB_DATABASE: gestor_citas_db
      MARIADB_USER: admin
      MARIADB_PASSWORD: abc123.
    ports:
      - "3306:3306"
    volumes:
      # Este volumen asegura que tus datos no se borren al apagar el contenedor
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
