services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: gestor_citas_db_container
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "3306:3306"
    volumes:
      # Este volumen asegura que tus datos no se borren al apagar el contenedor
      - mariadb_data:/var/lib/mysql

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: gestor_citas_frontend_container
    restart: always
    env_file:
      - ./frontend/.env
    ports:
      - "5173:80"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: gestor_citas_backend_container
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "9001:9001"
    depends_on:
      - db

volumes:
  mariadb_data:
