services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: gestor_citas_db_container
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "3306:3306"
    volumes:
      # Este volumen asegura que tus datos no se borren al apagar el contenedor
      - mariadb_data:/var/lib/mysql

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: gestor_citas_frontend_container
    restart: always
    env_file:
      - ./frontend/.env

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: gestor_citas_backend_container
    restart: always
    env_file:
      - ./backend/.env
    depends_on:
      - db

  caddy_proxy:
    image: caddy:2-alpine
    container_name: caddy_proxy
    restart: always
    ports:
      - "80:80"    # Puerto estándar de internet HTTP
      - "443:443"  # Puerto estándar seguro HTTPS (SSL)
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - frontend
      - backend    

volumes:
  mariadb_data:
  caddy_data:   
  caddy_config: